/** Code generated by GenAI */

import org.apache.batik.transcoder.image.PNGTranscoder
import org.apache.batik.transcoder.{TranscoderInput, TranscoderOutput}
import org.apache.fop.svg.PDFTranscoder

import java.io.{FileOutputStream, StringReader}
import java.nio.file.{Files, Path}

/** Renders an AMECOS history in the horizontal process/timeline style used by the AMECOS slides. */
object HistoryDiagram:
  private val processColors =
    Vector("#e5232b", "#4f83c2", "#16a765", "#8a4bb8", "#e28a1a", "#d14b9b", "#1596a8", "#6f7782")

  private val pageWidth = 1400
  private val leftMargin = 150
  private val rightMargin = 80
  private val topMargin = 100
  private val rowHeight = 125
  private val axisLength = pageWidth - leftMargin - rightMargin
  private val timeAxisLength = axisLength - 45

  /** Produces a standalone SVG with process timelines and interval-shaped op-exes. */
  def render(history: History, order: Order): String =
    val operations = history.opExes.toList.sortBy(operationKey)
    val processes = operations.map(_.process.name).distinct.sorted
    val colors = processes.zipWithIndex.map { case (name, index) => name -> colorForProcess(index) }.toMap
    val minTime = operations.map(_.interval._1).minOption.getOrElse(0)
    val maxTime = operations.map(_.interval._2).maxOption.getOrElse(minTime + 1)
    val timeRange = math.max(1, maxTime - minTime)
    val rowByProcess = processes.zipWithIndex.map { case (name, index) => name -> (topMargin + index * rowHeight + 55.0) }.toMap
    val placements = operations.map(operation =>
      Placement(
        operation,
        timeX(operation.interval._1, minTime, timeRange),
        timeX(operation.interval._2, minTime, timeRange),
        rowByProcess(operation.process.name),
        colors(operation.process.name)
      )
    )
    val placementByOperation = placements.map(p => p.operation -> p).toMap

    val body = collection.mutable.ArrayBuffer[String]()
    body += "<defs>"
    body += "<marker id=\"axis-arrow\" markerWidth=\"12\" markerHeight=\"12\" refX=\"9\" refY=\"4\" orient=\"auto\"><path d=\"M0,0 L0,8 L10,4 z\" fill=\"#111827\"/></marker>"
    body += "<marker id=\"order-arrow\" markerWidth=\"10\" markerHeight=\"10\" refX=\"8\" refY=\"4\" orient=\"auto\"><path d=\"M0,0 L0,8 L9,4 z\" fill=\"#4b5563\"/></marker>"
    colors.values.toSet.foreach(color =>
      body += s"<marker id=\"${markerId(color, false)}\" markerUnits=\"userSpaceOnUse\" markerWidth=\"10\" markerHeight=\"10\" refX=\"5\" refY=\"4\" orient=\"auto\"><path d=\"M0,0 L10,4 L0,8 z\" fill=\"$color\"/></marker>"
      body += s"<marker id=\"${markerId(color, true)}\" markerUnits=\"userSpaceOnUse\" markerWidth=\"10\" markerHeight=\"10\" refX=\"5\" refY=\"4\" orient=\"auto\"><path d=\"M10,0 L0,4 L10,8 z\" fill=\"$color\"/></marker>"
    )
    body += "</defs>"
    body += s"<rect width=\"$pageWidth\" height=\"${diagramHeight(processes.size)}\" fill=\"white\"/>"
    body += s"<text x=\"${pageWidth - rightMargin}\" y=\"${diagramHeight(processes.size) - 15}\" text-anchor=\"end\" class=\"time-title\">time</text>"

    processes.foreach { process =>
      val y = rowByProcess(process)
      body += s"<text x=\"${leftMargin - 25}\" y=\"${y + 6}\" text-anchor=\"end\" class=\"process\">${escape(process)}</text>"
      body += s"<line x1=\"$leftMargin\" y1=\"$y\" x2=\"${leftMargin + axisLength}\" y2=\"$y\" class=\"axis\" marker-end=\"url(#axis-arrow)\"/>"
    }

    placements.foreach { placement =>
      val xStart = math.min(placement.xStart, placement.xEnd)
      val xEnd = math.max(placement.xStart, placement.xEnd)
      val labelY = if labelAbove(placement.operation, operations) then placement.y - 22 else placement.y + 42
      val timeY = if labelAbove(placement.operation, operations) then placement.y - 7 else placement.y + 58
      val labelAnchor = if xEnd - xStart < 100 then "middle" else "middle"
      val labelX = (xStart + xEnd) / 2
      body += s"<line x1=\"$xStart\" y1=\"${placement.y}\" x2=\"$xEnd\" y2=\"${placement.y}\" stroke=\"${placement.color}\" stroke-width=\"7\" marker-start=\"url(#${markerId(placement.color, true)})\" marker-end=\"url(#${markerId(placement.color, false)})\"/>"
      body += s"<circle cx=\"$xStart\" cy=\"${placement.y}\" r=\"8\" fill=\"${placement.color}\" stroke=\"#1f2937\" stroke-width=\"2\"/>"
      body += s"<circle cx=\"$xEnd\" cy=\"${placement.y}\" r=\"8\" fill=\"${placement.color}\" stroke=\"#1f2937\" stroke-width=\"2\"/>"
      body += s"<text x=\"$labelX\" y=\"$labelY\" text-anchor=\"$labelAnchor\" class=\"operation\" fill=\"${placement.color}\">${escape(operationLabel(placement.operation))}</text>"
      body += s"<text x=\"$labelX\" y=\"$timeY\" text-anchor=\"$labelAnchor\" class=\"interval\">(${placement.operation.interval._1}, ${placement.operation.interval._2})</text>"
    }

    operations.foreach { from =>
      order.next(from).toList.sortBy(operationKey).foreach { to =>
        val source = placementByOperation(from)
        val target = placementByOperation(to)
        val controlY = (source.y + target.y) / 2 + (if source.y < target.y then 28 else -28)
        body += s"<path d=\"M ${source.xEnd} ${source.y} Q ${(source.xEnd + target.xStart) / 2} $controlY ${target.xStart} ${target.y}\" class=\"ordering\" marker-end=\"url(#order-arrow)\"/>"
      }
    }

    val height = diagramHeight(processes.size)
    s"""<?xml version="1.0" encoding="UTF-8"?>
       |<svg xmlns="http://www.w3.org/2000/svg" width="$pageWidth" height="$height" viewBox="0 0 $pageWidth $height">
       |<style>
       |  .time-title { font: italic 20px serif; fill: #111827; }
       |  .process { font: italic 24px serif; fill: #111827; }
       |  .operation { font: italic 20px serif; }
       |  .interval { font: 13px sans-serif; fill: #4b5563; }
       |  .axis { stroke: #111827; stroke-width: 2; }
       |  .ordering { fill: none; stroke: #4b5563; stroke-width: 2; stroke-dasharray: 8 6; }
       |</style>
       |${body.mkString("\n")}
       |</svg>
       |""".stripMargin

  private def timeX(time: Int, minTime: Int, timeRange: Int): Double =
    leftMargin + (time - minTime).toDouble / timeRange * timeAxisLength

  private def diagramHeight(processCount: Int): Int =
    math.max(250, topMargin + processCount * rowHeight + 45)

  private def labelAbove(operation: Operation, operations: List[Operation]): Boolean =
    operations.filter(_.process == operation.process).sortBy(operationKey).indexOf(operation) % 2 == 0

  private def operationKey(operation: Operation): (String, Int, Int, String, String, String) =
    (operation.process.name, operation.interval._1, operation.interval._2, operation.obj.name, operation.name, operation.input.mkString(","))

  private def markerId(color: String, reverse: Boolean): String =
    "arrow-" + math.abs(color.hashCode) + (if reverse then "-reverse" else "")

  private def colorForProcess(index: Int): String =
    if index < processColors.size then processColors(index)
    else s"hsl(${(index * 137) % 360}, 70%, 45%)"

  private def operationLabel(operation: Operation): String =
    val args = operation.input.mkString("(", ", ", ")")
    val result = operation.output match
      case UnitData() => ""
      case value => "/" + value
    s"${operation.obj.name}.${operation.name}$args$result"

  private def escape(value: String): String =
    value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")

  /** Writes the custom SVG directly or converts it to PNG/PDF. */
  def renderImage(svg: String, output: Path, format: String): Unit =
    format.toLowerCase match
      case "svg" => Files.writeString(output, svg)
      case "png" => transcode(svg, output, new PNGTranscoder)
      case "pdf" => transcode(svg, output, new PDFTranscoder)
      case value => throw new IllegalArgumentException(s"Unsupported diagram format: $value")

  private def transcode(svg: String, output: Path, transcoder: org.apache.batik.transcoder.Transcoder): Unit =
    val stream = new FileOutputStream(output.toFile)
    try transcoder.transcode(new TranscoderInput(new StringReader(svg)), new TranscoderOutput(stream))
    finally stream.close()

  private case class Placement(operation: Operation, xStart: Double, xEnd: Double, y: Double, color: String)
