/** Code generated by GenAI */
import Amecos.{AmecosLexer, AmecosParser}
import Ast.App
import org.antlr.v4.runtime.*

import java.nio.file.Paths

/** Parses an AMECOS file into the application AST. */
object HistoryParser:
  def parseFile(path: String): App =
    val sourcePath = Paths.get(path).toAbsolutePath.normalize()
    val input = CharStreams.fromString(ImportResolver.expand(sourcePath), sourcePath.toString)
    val lexer = new AmecosLexer(input)
    val tokens = new CommonTokenStream(lexer)
    val parser = new AmecosParser(tokens)

    parser.removeErrorListeners()
    parser.addErrorListener(new BaseErrorListener {
      override def syntaxError(
                                recognizer: Recognizer[?, ?],
                                offendingSymbol: Any,
                                line: Int,
                                charPositionInLine: Int,
                                msg: String,
                                e: RecognitionException
                              ): Unit =
        throw new RuntimeException(s"Syntax error at $line:$charPositionInLine - $msg")
    })

    new AstBuilder().visitApp(parser.app())
